name: Build APK

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        flavor: [FDroid, PlayStore]
        build-type: [Debug]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      with:
        api-level: 36
        build-tools: 36.0.0
        ndk-version: 28.2.13676358
        
    - name: Cache Gradle packages
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
          
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Create local.properties
      run: |
        echo "SIGNALING_SERVER_DEV=\"\"" >> local.properties
        echo "CLOUD_PROJECT_NUMBER_DEV=\"\"" >> local.properties
        echo "SIGNALING_SERVER_RELEASE=\"\"" >> local.properties
        echo "CLOUD_PROJECT_NUMBER_RELEASE=\"\"" >> local.properties
        echo "ad.pubId=\"\"" >> local.properties
        
    - name: Build Debug APK
      run: ./gradlew assemble${{ matrix.flavor }}${{ matrix.build-type }} --stacktrace
      
    - name: Find APK files
      run: find . -name "*.apk" -type f
        
    - name: Save APK as artifact
      uses: actions/upload-artifact@v4
      with:
        name: ScreenStream-${{ matrix.flavor }}-${{ matrix.build-type }}
        path: "**/*.apk"
        retention-days: 7

  quick-build:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      with:
        api-level: 36
        build-tools: 36.0.0
        ndk-version: 28.2.13676358
        
    - name: Cache Gradle packages
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
          
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Create local.properties
      run: |
        echo "SIGNALING_SERVER_DEV=\"\"" >> local.properties
        echo "CLOUD_PROJECT_NUMBER_DEV=\"\"" >> local.properties
        echo "SIGNALING_SERVER_RELEASE=\"\"" >> local.properties
        echo "CLOUD_PROJECT_NUMBER_RELEASE=\"\"" >> local.properties
        echo "ad.pubId=\"\"" >> local.properties
        
    - name: Build FDroid Debug (fastest, no Firebase)
      run: ./gradlew assembleFDroidDebug --stacktrace
        
    - name: Find APK files
      run: find . -name "*.apk" -type f
        
    - name: Save APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: ScreenStream-FDroid-Debug-Quick
        path: "**/*.apk"
        retention-days: 7
